<?php

namespace Anva\MailClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImapContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImapContactsRepository extends EntityRepository
{
}
