<?php

namespace Anva\MailClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImapAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImapAccountRepository extends EntityRepository
{
}
