<?php

namespace Anva\MailClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImapMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImapMailRepository extends EntityRepository
{
}
